
name: Consumer Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    paths:
      - "consumer/**"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.22.0'
      - name: Git config for private access
        run: git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_ACCESS_TOKEN }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          workdir: consumer
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_ACCESS_TOKEN }}
          ECR_REPOSITORY: ${{ steps.login-ecr.outputs.registry }}